// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbSK0EQpYLe_s4ffwWpsdITx_9w4onCVw',
    appId: '1:434072482323:web:7a3118e4ed48c39141c5e6',
    messagingSenderId: '434072482323',
    projectId: 'homeeaseai',
    authDomain: 'homeeaseai.firebaseapp.com',
    storageBucket: 'homeeaseai.firebasestorage.app',
    measurementId: 'G-XJYKDR5XEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClmDcdT8Oqs-sm5Vbu_bcv1Y-N8olHPwo',
    appId: '1:434072482323:android:171a61143f6732ba41c5e6',
    messagingSenderId: '434072482323',
    projectId: 'homeeaseai',
    storageBucket: 'homeeaseai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5TH05TkwK5d_8WPlCQV0bLl2CoDe_Q-c',
    appId: '1:434072482323:ios:b332cdb2bb6b05f241c5e6',
    messagingSenderId: '434072482323',
    projectId: 'homeeaseai',
    storageBucket: 'homeeaseai.firebasestorage.app',
    iosBundleId: 'com.example.day35',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5TH05TkwK5d_8WPlCQV0bLl2CoDe_Q-c',
    appId: '1:434072482323:ios:6eb45a40390bc47c41c5e6',
    messagingSenderId: '434072482323',
    projectId: 'homeeaseai',
    storageBucket: 'homeeaseai.firebasestorage.app',
    iosBundleId: 'none',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbSK0EQpYLe_s4ffwWpsdITx_9w4onCVw',
    appId: '1:434072482323:web:6dc2bbe1fe4bc71341c5e6',
    messagingSenderId: '434072482323',
    projectId: 'homeeaseai',
    authDomain: 'homeeaseai.firebaseapp.com',
    storageBucket: 'homeeaseai.firebasestorage.app',
    measurementId: 'G-4W7RMPR6ZZ',
  );
}
